---
#ansible_user: Ansible
#ansible_ssh_pass: ansible123
#ansible_connection: network_cli
#ansible_network_os: eos
ansible_connection: httpapi 
ansible_httpapi_use_ssl: yes
become_method: enable
ansible_httpapi_validate_certs: no
#ansible_become: yes
#ansible_become_method: enable

ansible_network_os: eos
ansible_connection: network_cli
ansible_user: ansible
ansible_ssh_pass: ansible123
ansible_become: yes
ansible_become_method: enable
