---
- name: Return Arista Network to Default
  hosts: leaf01
  tasks:
    - name: Delete Configuration
      eos_config:
        lines:
          - default interface ethernet 1-9
          - no management api http-commands
          - no router bgp
          - no vlan 2-4090
          - no ip name-server
          - no ip prefix-list loopback
          - no route-map loopback
          - no interface Vxlan1
          - no ip route vrf MGMT 10.8.0.0/24 192.168.122.5
          - no ip route vrf MGMT 172.20.1.0/24 192.168.122.5
          - no ip route vrf MGMT 192.168.1.0/24 192.168.122.5
   
        # src_format: set
